import { Router, type IRouter } from "express";
import healthRouter from "./health";
import categoriesRouter from "./categories";
import productsRouter from "./products";
import cartRouter from "./cart";
import ordersRouter from "./orders";
import paymentsRouter from "./payments";
import authRouter from "./auth";
import authGoogleRouter from "./auth-google";
import authOtpRouter from "./auth-otp";
import adminRouter from "./admin";
import mediaRouter from "./media";
import reviewsRouter from "./reviews";
import deliveryRouter from "./delivery";
import homepageRouter from "./homepage";
import newsletterRouter from "./newsletter";
import blogRouter from "./blog";
import siteSettingsRouter from "./site-settings";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(authGoogleRouter);
router.use(authOtpRouter);
router.use(categoriesRouter);
router.use(productsRouter);
router.use(cartRouter);
router.use(ordersRouter);
router.use(paymentsRouter);
router.use(adminRouter);
router.use(mediaRouter);
router.use(reviewsRouter);
router.use(deliveryRouter);
router.use(homepageRouter);
router.use(newsletterRouter);
router.use(blogRouter);
router.use(siteSettingsRouter);

export default router;
